/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"


//==============================================================================
SynthuckAudioProcessor::SynthuckAudioProcessor()
:   m_pSineGenerator(new SineGenerator)
{
}

SynthuckAudioProcessor::~SynthuckAudioProcessor()
{
}

//==============================================================================
const String SynthuckAudioProcessor::getName() const
{
    return JucePlugin_Name;
}

int SynthuckAudioProcessor::getNumParameters()
{
    return 0;
}

float SynthuckAudioProcessor::getParameter (int index)
{
    return 0.0f;
}

void SynthuckAudioProcessor::setParameter (int index, float newValue)
{
}

const String SynthuckAudioProcessor::getParameterName (int index)
{
    return String();
}

const String SynthuckAudioProcessor::getParameterText (int index)
{
    return String();
}

const String SynthuckAudioProcessor::getInputChannelName (int channelIndex) const
{
    return String (channelIndex + 1);
}

const String SynthuckAudioProcessor::getOutputChannelName (int channelIndex) const
{
    return String (channelIndex + 1);
}

bool SynthuckAudioProcessor::isInputChannelStereoPair (int index) const
{
    return true;
}

bool SynthuckAudioProcessor::isOutputChannelStereoPair (int index) const
{
    return true;
}

bool SynthuckAudioProcessor::acceptsMidi() const
{
   #if JucePlugin_WantsMidiInput
    return true;
   #else
    return false;
   #endif
}

bool SynthuckAudioProcessor::producesMidi() const
{
   #if JucePlugin_ProducesMidiOutput
    return true;
   #else
    return false;
   #endif
}

bool SynthuckAudioProcessor::silenceInProducesSilenceOut() const
{
    return false;
}

double SynthuckAudioProcessor::getTailLengthSeconds() const
{
    return 0.0;
}

int SynthuckAudioProcessor::getNumPrograms()
{
    return 1;   // NB: some hosts don't cope very well if you tell them there are 0 programs,
                // so this should be at least 1, even if you're not really implementing programs.
}

int SynthuckAudioProcessor::getCurrentProgram()
{
    return 0;
}

void SynthuckAudioProcessor::setCurrentProgram (int index)
{
}

const String SynthuckAudioProcessor::getProgramName (int index)
{
    return String();
}

void SynthuckAudioProcessor::changeProgramName (int index, const String& newName)
{
}

//==============================================================================
void SynthuckAudioProcessor::prepareToPlay (double sampleRate, int samplesPerBlock)
{
    m_pSineGenerator->initialise(sampleRate);
}

void SynthuckAudioProcessor::releaseResources()
{
    // When playback stops, you can use this as an opportunity to free up any
    // spare memory, etc.
}

void SynthuckAudioProcessor::processBlock (AudioSampleBuffer& buffer, MidiBuffer& midiMessages)
{
    m_pSineGenerator->process(buffer, midiMessages);
    
    for (int i = 1; i < getNumOutputChannels(); ++i)
    {
        buffer.clear (i, 0, buffer.getNumSamples());
    }
}

//==============================================================================
bool SynthuckAudioProcessor::hasEditor() const
{
    return true; // (change this to false if you choose to not supply an editor)
}

AudioProcessorEditor* SynthuckAudioProcessor::createEditor()
{
    return new SynthuckAudioProcessorEditor (*this);
}

//==============================================================================
void SynthuckAudioProcessor::getStateInformation (MemoryBlock& destData)
{
    // You should use this method to store your parameters in the memory block.
    // You could do that either as raw data, or use the XML or ValueTree classes
    // as intermediaries to make it easy to save and load complex data.
}

void SynthuckAudioProcessor::setStateInformation (const void* data, int sizeInBytes)
{
    // You should use this method to restore your parameters from this memory block,
    // whose contents will have been created by the getStateInformation() call.
}

//==============================================================================
// This creates new instances of the plugin..
AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new SynthuckAudioProcessor();
}
